version: '3'

services:
  mongo-express:
    container_name: mongo-express-app-pedido
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo  
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongo-db-app-pedido
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass123
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

  # api:
    # container_name: app-pedido
    # build:
      # context: .  # Caminho para o Dockerfile da aplicação
    # environment:
      # DB_PASSWORD: pass123
      # DB_USER: admin
      # DB_HOST: mongo  
    # ports:
      # - "8082:80"
    # depends_on:
      # - mongo
    # networks:
      # - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge
